# Lesson 3 Proxy Makefile
.PHONY: install lab train generate chat format clean

install:
	$(MAKE) -C .. install

lab:
	$(MAKE) -C .. lab

train:
	$(MAKE) -C .. train

generate:
	$(MAKE) -C .. generate

chat:
	$(MAKE) -C .. chat

format:
	$(MAKE) -C .. format

clean:
	$(MAKE) -C .. clean
